export const CREATE_EVENT = 'CREATE_EVENT';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const EDIT_EVENT_DETAILS_SUCCESS = 'EDIT_EVENT_DETAILS_SUCCESS';
export const CANCEL_EVENT_SUCCESS = 'CANCEL_EVENT_SUCCESS';
export const RESET_STATUS = 'RESET_STATUS';
