export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_PROFILE_PICTURE = 'SET_PROFILE_PICTURE';
