# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yelp_id', models.IntegerField(null=True)),
                ('datetime', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('invite_code', models.CharField(max_length=200, null=True)),
                ('voting_deadline', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('radius', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceCuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Cuisine')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Preference')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yelp_id', models.IntegerField()),
                ('json', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yelp_id', models.IntegerField()),
                ('right_swipe_count', models.IntegerField(default=0)),
                ('left_swipe_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Event')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='swipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.User'),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Preference'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.EventDetail'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.User'),
        ),
    ]
