# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20170302_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=49.2827, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=123.1207, max_digits=9),
            preserve_default=False,
        ),
    ]
