# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 16:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0005_auto_20170304_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventUserAttach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='eventuserattach',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Event'),
        ),
        migrations.AddField(
            model_name='eventuserattach',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
