# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20170305_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuisine',
            old_name='type',
            new_name='category',
        ),
        migrations.AddField(
            model_name='cuisine',
            name='name',
            field=models.CharField(default='name', max_length=200),
            preserve_default=False,
        ),
    ]
