# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20170308_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetail',
            name='voting_deadline',
        ),
        migrations.AddField(
            model_name='event',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='round_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='round_start',
            field=models.DateTimeField(default=None),
        ),
    ]
