# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20170308_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetail',
            name='yelp_id',
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Restaurant'),
        ),
    ]
