# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20170320_1641'),
        ('server', '0009_auto_20170321_0930'),
    ]

    operations = [
    ]
