# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_merge_20170322_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='round_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
