# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_userfcm'),
        ('server', '0011_auto_20170322_1026'),
    ]

    operations = [
    ]
