# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_merge_20170327_2254'),
        ('server', '0012_merge_20170327_0133'),
    ]

    operations = [
    ]
