# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_eventuserattach_last_round_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuserattach',
            name='last_round_voted',
            field=models.IntegerField(null=True),
        ),
    ]
