# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_eventuserattach_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cuisines',
            field=models.ManyToManyField(to='server.Cuisine'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
