# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_swipe_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='randomize_tie',
            field=models.BooleanField(default=False),
        ),
    ]
