# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_event_randomize_tie'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='competitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Tournament'),
        ),
    ]
